### ISSUE TITLE
Change in "six" import

### ISSUE THREAD

**Issue by luccaportes** [johny-c/pylmnn#2]
Hi, I suggest a small change in line 27 of ```pylmnn.py```. Which is:

```from sklearn.externals.six import integer_types, string_types```

Which raises the following warning when executed:

```
DeprecationWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", DeprecationWarning)
```

So in order to maintain compatibility with both older and future versions, I propose something like this:

```
try:
    from six import integer_types, string_types
except ImportError:
    try:
        from sklearn.externals.six import integer_types, string_types
    except ImportError:
        raise ImportError("The module six must be installed or the version of scikit-learn version must be < 0.23")
```

I'll open a pull request in case you think it is a good idea.

**Comment by johny-c** [comment]
Thanks for raising this. There is also another import of sklearn.externals.six in test_lmnn.py. If you want to do the same there and check that the tests pass for 2.7 and 3.6 at least, I would be happy to merge a PR. Otherwise I will do it as soon as I find some time.

**Comment by luccaportes** [comment]
Done, already updated the PR. Both tests passed, for 2.7, 3.6, and 3.7. However, you should know that the tests for test_bayesopt.py are failing, but not because of this change, they are failing in the current master too.

**Comment by johny-c** [comment]
Thanks for catching this. I will upload a new version soon.
