### ISSUE TITLE
Option to save the fit model? 

### ISSUE THREAD

**Issue by GeorgePearse** [johny-c/pylmnn#7]
The training step takes a long time. Is there way to save the model after the .fit method. If not should I submit a PR to enable it?

**Comment by johny-c** [comment]
Have you checked the `callback` argument? This should be a function that is called after every iteration with the current solution.

**Comment by GeorgePearse** [comment]
Cheers for getting back to me (and for the package in the first place, served me much better than the alternativesI tried). I was thinking more of a model.save('<file-name>') format for once the training is complete. V. common to experiment lots and only care about saving the model once you achieve good results. At least in my workflows.

**Comment by johny-c** [comment]
Thanks! Glad to hear this is useful. Regarding the issue, it sounds more like something solvable with an experiment tracking library. A couple of options I have personally used in the past are [sacred](https://github.com/IDSIA/sacred) and [mlflow](https://github.com/mlflow/mlflow). If you want something simpler, you could just use `pickle`.
